server:
  port: 8104
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nace
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true